### ISSUE TITLE
Is necessary this children?

### ISSUE THREAD

**Issue by macabeus** [kmck/react-hex-editor#2]
I'm reading the code source of this package, and I noticed that `HexEditorBody` could receive a children and render that. But I can't understand very well how it could be useful.

I think that we could remove this line:
https://github.com/kmck/react-hex-editor/blob/ac62946ecf24626ec68a51622b098d409d68bb53/src/components/HexEditor.tsx#L857

And removing that, we are able to remove too the component `HexEditorBody`, that its only purpose is handle this possible children.

**Comment by kmck** [comment]
this allows the addition of other components alongside the hex editor data view. i added it to support custom data visualization (rather than just ascii), such as interpreting the value as image data and rendering to canvas.

this isn't particularly well documented, so i can understand why you'd be curious about it!
